config/routes.rb
Rails.application.routes.draw do
  #root 'tasks#index'
  root 'homes#index'
  devise_for :users, controllers: { registrations: 'registrations' , sessions: 'sessions' }
  #devise_for :users
 
  #resources :devise
   #resources :sessions
  #    get "log_in" => "sessions#new", :as => "log_in"
  # get "sign_up" => "users#new", :as => "sign_up"
  #post "/homes/:id/accept", to: "homes#accept" , as:'accept'

   resources :homes do 
   member do
    post :accept
    post :reject
  
     resources  :tasks do
       member do
       post :finish_work
       post :in_progress
       post :start_work
        end 
    end 
   end
end
  




   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
	
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :tasks


end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @user =User.all
  end
  def show
    @user = User.find(params[:id])
  end 
  def accept
    @user = User.find(params[:id])
    @user.update(usersinput: true)
    redirect_to root_path
  end
   def reject

    @user = User.find(params[:id])
    @user.update(usersinput: false)
    redirect_to root_path
  end

end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
   prepend_before_action :require_no_authentication, only: [:new, :create, :cancel]
  prepend_before_action :authenticate_scope!, only: [:edit, :update, :destroy]
  prepend_before_action :set_minimum_password_length, only: [:new, :edit]

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  
   def create

      build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      # if resource.active_for_authentication?
        
      #   sign_up(resource_name, resource)
        
      #   respond_with resource, location: after_sign_up_path_for(resource)
      # else
      #   set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
      #   expire_data_after_sign_in!
      #   respond_with resource, location: after_inactive_sign_up_path_for(resource)
      # end
      redirect_to root_path
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/sessions_controller.rb
# # frozen_string_literal: true

class SessionsController < Devise::SessionsController
  #   prepend_before_action :require_no_authentication, only: [:new, :create]
  # prepend_before_action :allow_params_authentication!, only: :create
  # prepend_before_action :verify_signed_out_user, only: :destroy
  # prepend_before_action(only: [:create, :destroy]) { request.env["devise.skip_timeout"] = true }
  # before_action :configure_sign_in_params, only: [:create]

  before_action :verify_user, only: :create

  # GET /resource/sign_in
   def new
    super 
    #   self.resource = resource_class.new(sign_in_params)
    # clean_up_passwords(resource)
    # yield resource if block_given?
    # respond_with(resource, serialize_options(resource))
    
  end
  # POST /resource/sign_in
    # def create
       
    # end

  def verify_user
    @user = User.find_by(email: params["user"]["email"])
    if @user.present?
      if @user.usersinput == false  
        flash[:alert] = "your account Reject !!"
        redirect_to user_session_path 
      elsif @user.usersinput == true  
           
      else 
        flash[:alert] = "your account not conform!!"
        redirect_to user_session_path
      end  
    end       
  end
  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
  
    @user = User.find(params[:task][:user_id])
    @task = @user.tasks.create(task_params)
    
    redirect_to home_path(@user)
  end 
  def start_work
    @task = Task.find(params[:id])
    @task.update(workstatus: "start work")

    redirect_to home_path(current_user)
  end
   def finish_work

    @task = Task.find(params[:id])
    @task.update(workstatus: "finish work")
    redirect_to home_path(current_user)
  end 
   def in_progress

    @task = Task.find(params[:id])
    @task.update(workstatus: "in_progress")
   redirect_to home_path(current_user)
  end

  private
    def task_params
      params.require(:task).permit(:name, :workstatus ,:user_id)
    end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/homes/index.html.erb
 
<%if current_user.usersinput == true %>   
    <table>
      <thead>
        <tr>
          <th>Name</th>
          
          <th colspan="3"></th>
        </tr>
      </thead>
        <%if current_user.typename == 'manejar'  %>
             <% User.all.reverse.each do |u| %>
             <tr>
                 <td> <%=  u.email%><td>
              <% if u.usersinput == true %>
              <td><strong>accepted</strong></td>	
              <td><%= link_to 'Show', home_path(u) %></td>
              <% elsif u.usersinput == false %>
              <td><strong>reject</strong></td>
               <% else  %>
              
                 <td><%=button_to 'accept', accept_home_path(u.id), method: :accept %></td>
                 <td><%=button_to 'reject', reject_home_path(u.id), method: :reject %></td>
                
                <%end%>
              

               <%end%>
           <%else%>
           <td><%= link_to 'Show', home_path(current_user.id) %></td>
          <%end%>

          </tr>
          <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
       
       
      </tbody>
    </table>

     <br>
    <% elsif current_user.usersinput == false %>
        <td><h1>reject</h1></td>
      <%= link_to "back", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
 <%else%>
  <td><h1>your account not conform</h1></td>
 <%= link_to "back", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        
<%end%>

app/views/homes/show.html.erb
<h1><%= @user.email %></h1>

<h2> task </h2>


<% @user.tasks.each do |task| %>
  <p>
    <strong>Task:</strong>
     <%= task.name %>
  </p>

  <p>
    <strong>Workstatus =></strong>
     <%if task.workstatus == "start work" %>
             <td><strong>start work</strong></td>  
             <% elsif task.workstatus ==  "finish work"%>
             <td><strong>finish work</strong></td>
              <% elsif task.workstatus ==  "in_progress"  %>
               <td><strong>in_progress</strong></td>
               <%else%>
                <td><strong>no response</strong></td>
             <%end%>

  </p>
   <%if current_user.typename == 'manejar'  %>
            <%if task.workstatus == "start work" %>
             <td><strong>start work</strong></td>  
             <% elsif task.workstatus ==  "finish work"%>
             <td><strong>finish work</strong></td>
              <% elsif task.workstatus ==  "in_progress"  %>
               <td><strong>in_progress</strong></td>
               <%else%>
                <td><strong>no response</strong></td>
             <%end%>
    <%else%>
    <tr>
        <td> 
     
      <%= button_to "start work" ,  start_work_task_path(task) , method: :start_work_task  %>
       <%= button_to "in_progress" , in_progress_task_path(task) , method: :in_progress_task %>
        <%= button_to "finish_work_task" , finish_work_task_path(task) , method: :finish_work %>
      </td><br>
      <%end%>
  </tr>
<% end %>

 <%if current_user.typename == 'manejar'  %>
  <%= form_with model: [ @user, @user.tasks.build ],url:tasks_path   do |form| %>
  <%#= form_for @user, :as => :user, :url => sign_in_path(@user) do |f| %>
   <%#= form_for @user,[ @user, @user.tasks.build ], url:tasks_path  do |form| %>
    <p>

       <%= form.label :name %><br>
      <%= form.text_field :name %>
  </p>
      <%= form.hidden_field :user_id, value: @user.id %>
             

  <p>
  	

  </p>
  <p>
    <%= form.submit %>
  </p>
  <%end%>
<% end %>





<%= button_to 'Back',  root_path , method: :get  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yuvasoft</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <h2><p class="notice"><%= notice %></p></h2>
       <h2><p class="alert"><%= alert %></p></h2>

    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% task.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
    </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<%= render "form", task: @task %>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<%= render "form", task: @task %>